name: CI Test

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Record start time
        run: echo "PIPELINE_START=$(date +%s)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dummy build step
        run: |
          echo "Simulating some work..."
          sleep 10
          echo "Done."

      - name: Calculate and print duration
        run: |
          END=$(date +%s)
          DURATION=$((END-PIPELINE_START))
          echo "Pipeline duration (seconds): $DURATION"
